{{- define "edge-endpoint.registry-credentials.podSpec" -}}
restartPolicy: Never
serviceAccountName: edge-endpoint-service-account

containers:
  - name: az-cli
    image: mcr.microsoft.com/azure-cli:2.60.0
    command:
      - /bin/sh
      - /app/init-azure-access-retrieve.sh
    env:
      - name: INTELLIOPTICS_ENDPOINT
        value: "{{ .Values.upstreamEndpoint }}"
      - name: INTELLIOPTICS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: IntelliOptics-api-token
            key: INTELLIOPTICS_API_TOKEN

    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-azure-access
        mountPath: /app/init-azure-access-retrieve.sh
        subPath: init-azure-access-retrieve.sh

  - name: kubectl
    image: bitnami/kubectl:1.30.0
    command:
      - /bin/sh
      - /app/init-azure-access-apply.sh
    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-azure-access
        mountPath: /app/init-azure-access-apply.sh
        subPath: init-azure-access-apply.sh
volumes:
  - name: init-azure-access
    configMap:
      name: init-azure-access
  - name: shared-volume
    emptyDir: {}
{{- end }}
