{{- define "edge-endpoint.registry-credentials.podSpec" -}}
restartPolicy: Never
serviceAccountName: edge-endpoint-service-account

containers:
  - name: aws-cli

    command:
      - /bin/sh
      - /app/init-aws-access-retrieve.sh
    env:
      - name: GROUNDLIGHT_ENDPOINT
        value: "{{ .Values.upstreamEndpoint }}"
      - name: INTELLIOPTICS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: groundlight-api-token
            key: INTELLIOPTICS_API_TOKEN

    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-aws-access
        mountPath: /app/init-aws-access-retrieve.sh
        subPath: init-aws-access-retrieve.sh

  - name: kubectl

    command:
      - /bin/sh
      - /app/init-aws-access-apply.sh
    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-aws-access
        mountPath: /app/init-aws-access-apply.sh
        subPath: init-aws-access-apply.sh
volumes:
  - name: init-aws-access
    configMap:
      name: init-aws-access
  - name: shared-volume
    emptyDir: {}
{{- end }}
