{{- define "edge-endpoint.registry-credentials.podSpec" -}}
restartPolicy: Never
serviceAccountName: edge-endpoint-service-account

containers:
  - name: azure-cli
    image: {{ .Values.registryCredentials.azureCliImage }}
    command:

      - /bin/bash
      - -c
      - |
        # ConfigMap mounts lack the execute bit, so run the script through bash.
        exec /bin/bash /app/init-aws-access-retrieve.sh

      - /bin/sh
      - /app/init-azure-access-retrieve.sh

    env:
      - name: INTELLIOPTICS_ENDPOINT
        value: "{{ .Values.upstreamEndpoint }}"
      - name: INTELLIOPTICS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: IntelliOptics-api-token
            key: INTELLIOPTICS_API_TOKEN
      - name: REGISTRY_PROVIDER
        value: "azure"
      - name: ACR_NAME
        value: "{{ .Values.acrName }}"
      - name: ACR_LOGIN_SERVER
        value: "{{ .Values.acrLoginServer }}"

    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-azure-access
        mountPath: /app/init-azure-access-retrieve.sh
        subPath: init-azure-access-retrieve.sh

  - name: kubectl
    image: {{ .Values.registryCredentials.kubectlImage }}
    command:
      - /bin/sh
      - /app/init-azure-access-apply.sh
    volumeMounts:
      - name: shared-volume
        mountPath: /shared
      - name: init-azure-access
        mountPath: /app/init-azure-access-apply.sh
        subPath: init-azure-access-apply.sh
volumes:
  - name: init-azure-access
    configMap:
      name: init-azure-access
  - name: shared-volume
    emptyDir: {}
{{- end }}

