{{- $loginServer := include "IntelliOptics-edge-endpoint.acrLoginServer" . -}}
{{- $username := required "You must supply azure.acr.username" .Values.azure.acr.username -}}
{{- $password := required "You must supply azure.acr.password" .Values.azure.acr.password -}}
{{- $auth := printf "%s:%s" $username $password | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $loginServer $username $password $auth | b64enc | quote }}
