# All this precise matching is considered poor practice in K8s, but it makes
# things more reliable here.
apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: "{{ .Values.persistentVolumeNameBase }}-{{ .Values.namespace }}"
  labels:
    edge-pv-for-namespace: {{ .Values.namespace }}
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  {{- with .Values.storage.data.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/intellioptics/edge
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: edge-endpoint-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.data.storageClassName }}
  storageClassName: {{ .Values.storage.data.storageClassName | quote }}
  {{- else }}
  storageClassName: ""
  {{- end }}
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      edge-pv-for-namespace: {{ .Values.namespace }}

