{{- $check := required "You must supply a IntelliOptics API token!" .Values.intelliopticsApiToken }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: validate-api-token-{{ .Values.namespace }}
  namespace: default
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0 # Do not retry the job
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: main

          env:
            - name: INTELLIOPTICS_ENDPOINT
              value: "{{ .Values.upstreamEndpoint }}"
            - name: INTELLIOPTICS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: IntelliOptics-api-token-validate-{{ .Values.namespace }}
                  key: INTELLIOPTICS_API_TOKEN
          command:
            - /bin/bash
            - /app/validate-api-token.sh
          volumeMounts:
            - name: validate-api-token-script
              mountPath: /app/validate-api-token.sh
              subPath: validate-api-token.sh
      volumes:
        - name: validate-api-token-script
          configMap:
            name: validate-api-token-script-{{ .Values.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validate-api-token-script-{{ .Values.namespace }}
  namespace: default
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"  # Ensure it runs before the job
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
data:
  validate-api-token.sh: |
    {{- tpl (.Files.Get "files/validate-api-token.sh") . | nindent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: IntelliOptics-api-token-validate-{{ .Values.namespace }}
  namespace: default
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"  # Ensure it runs before the job
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
type: Opaque
data:
  INTELLIOPTICS_API_TOKEN: {{ .Values.intelliopticsApiToken | b64enc | quote }}


