apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: acrintellioptics.azurecr.io/intellioptics/edge-endpoint:latest
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: pinamod-bootstrap
        image: acrintellioptics.azurecr.io/intellioptics/pinamod-artifacts:latest
        command:
        - sh
        - -c
        - |
          set -eu
          mkdir -p "${PINAMOD_DIR}"
          if [ ! -d /pinamod ]; then
            echo "Expected pinamod artifacts at /pinamod" >&2
            exit 1
          fi
          find "${PINAMOD_DIR}" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
          cp -a /pinamod/. "${PINAMOD_DIR}/"
        env:
        - name: PINAMOD_DIR
          value: /opt/models/pinamod-public/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        persistentVolumeClaim:
          claimName: edge-endpoint-pvc
  backoffLimit: 2


