apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
{{- if .Values.registryCredentialsSecretName }}
      imagePullSecrets:
        - name: {{ .Values.registryCredentialsSecretName }}
{{- end }}
      containers:
      - name: image-puller
        image: acrintellioptics.azurecr.io/intellioptics/edge-endpoint:latest
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod

        command: ['sh', '-c', 'mkdir -p $PINAMOD_DIR; aws s3 sync s3://pinamod-artifacts-public/pinamod $PINAMOD_DIR --delete']
        env:
        - name: PINAMOD_DIR
          value: /opt/models/pinamod-public/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
{{- if .Values.modelSyncCredentialsSecretName }}
        - name: object-store-credentials
          mountPath: /root/.aws
{{- end }}
      volumes:
      - name: pina-models
        persistentVolumeClaim:
          claimName: edge-endpoint-pvc
{{- if .Values.modelSyncCredentialsSecretName }}
      - name: object-store-credentials
        secret:
          secretName: {{ .Values.modelSyncCredentialsSecretName }}
          optional: true
{{- end }}
  backoffLimit: 2


