apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: {{ printf "%s/intellioptics/edge-endpoint:%s" .Values.azure.loginServer (include "IntelliOptics-edge-endpoint.edgeEndpointTag" .) }}
        imagePullPolicy: "{{ include "IntelliOptics-edge-endpoint.edgeEndpointPullPolicy" . }}"
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        image: {{ printf "%s/intellioptics/edge-endpoint:%s" .Values.azure.loginServer (include "IntelliOptics-edge-endpoint.inferenceTag" .) }}
        imagePullPolicy: "{{ include "IntelliOptics-edge-endpoint.inferencePullPolicy" . }}"
        command: ['sh', '-c', 'mkdir -p "$PINAMOD_DIR"; az storage blob download-batch --source "${PINAMOD_CONTAINER:-pinamod}" --destination "$PINAMOD_DIR" --connection-string "$AZURE_STORAGE_CONNECTION_STRING" --pattern "*" --no-progress']
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-credentials
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: PINAMOD_CONTAINER
          value: {{ .Values.azure.storage.pinamodContainer | default "pinamod" | quote }}
        - name: PINAMOD_DIR
          value: /opt/models/pinamod-public/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        persistentVolumeClaim:
          claimName: edge-endpoint-pvc
  backoffLimit: 2


