apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: {{ include "IntelliOptics-edge-endpoint.inferenceImage" . }}
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod

        command: ['sh', '-c', 'mkdir -p $PINAMOD_DIR && az storage blob download-batch --source $AZURE_STORAGE_CONTAINER --destination $PINAMOD_DIR --connection-string "$AZURE_STORAGE_CONNECTION_STRING" --pattern "*" --overwrite']
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: connection_string
        - name: AZURE_STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: container
        - name: PINAMOD_DIR
          value: /opt/models/pinamod-public/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        persistentVolumeClaim:
          claimName: edge-endpoint-pvc
      - name: azure-storage
        secret:
          secretName: azure-storage
  backoffLimit: 2


