apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: {{ .Values.edgeEndpointImage }}:{{ .Values.edgeEndpointTag }}
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        command: ['sh', '-c', 'echo "Syncing models from Azure Storage to $PINAMOD_DIR"']
        env:
        - name: PINAMOD_DIR
          value: /opt/models/pinamod-public/pinamod
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-credentials
              key: AZURE_STORAGE_CONNECTION_STRING
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        persistentVolumeClaim:
          claimName: edge-endpoint-pvc
  backoffLimit: 2
