apiVersion: batch/v1
kind: Job
metadata:
  name: create-acr-creds
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "IntelliOptics-edge-endpoint.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
    {{- include "edge-endpoint.registry-credentials.podSpec" . | nindent 6 }}

