apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        image: acrintellioptics.azurecr.io/intellioptics/edge-endpoint:latest
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        image: acrintellioptics.azurecr.io/intellioptics/edge-endpoint:latest
        command: ['sh', '-c', 'mkdir -p "$PINAMOD_DIR" && az storage blob download-batch --source "${PINAMOD_CONTAINER:-pinamod}" --destination "$PINAMOD_DIR" --connection-string "$AZURE_STORAGE_CONNECTION_STRING" --pattern "*" --no-progress']
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-credentials
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: PINAMOD_CONTAINER
          value: pinamod
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/intellioptics/edge/pinamod-public
          type: Directory
  backoffLimit: 2


