apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller
        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        command: ['sh', '-c', 'echo "Syncing models from Azure Storage to $PINAMOD_DIR"']
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage-credentials
              key: AZURE_STORAGE_CONNECTION_STRING
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/intellioptics/edge/pinamod-public
          type: Directory
  backoffLimit: 2
