apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller

        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod

        command: [
          "/bin/sh",
          "-c",
          "/intellioptics-edge/deploy/bin/sync-pinamod.sh"
        ]
        env:
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: client_id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: client_secret
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: tenant_id
        - name: PINAMOD_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: pinamod-storage
              key: storage_account
        - name: PINAMOD_STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: pinamod-storage
              key: storage_container
        - name: PINAMOD_STORAGE_PREFIX
          valueFrom:
            secretKeyRef:
              name: pinamod-storage
              key: storage_prefix
              optional: true
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/intellioptics/edge/pinamod-public
          type: Directory
  backoffLimit: 2


