apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller

        command: ["echo", "Successfully pulled image to warm cache"]
      # The AWS CLI tooling previously synchronized the public PINAMOD artifacts at runtime.
      # This is no longer required because models are now fetched directly through the
      # IntelliOptics API when detectors start up, so we simply warm the image cache here.
  backoffLimit: 2


