apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller

        command: ["echo", "Successfully pulled image to warm cache"]
  backoffLimit: 2


