apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller

        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod

        command: ['sh', '-c', 'mkdir -p $PINAMOD_DIR && az storage blob download-batch --source $AZURE_STORAGE_CONTAINER --destination $PINAMOD_DIR --connection-string "$AZURE_STORAGE_CONNECTION_STRING" --pattern "*" --overwrite']
        env:
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: connection_string
        - name: AZURE_STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: azure-storage
              key: container
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/intellioptics/edge/pinamod-public
          type: Directory
  backoffLimit: 2


