apiVersion: batch/v1
kind: Job
metadata:
  name: warmup-inference-model
spec:
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: image-puller

        command: ["echo", "Successfully pulled image to warm cache"]
      - name: sync-pinamod
        image: mcr.microsoft.com/azure-cli:2.53.0
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - >-
          mkdir -p "$PINAMOD_DIR" && rm -rf "$PINAMOD_DIR"/* &&
          az storage blob download-batch
            --account-name "$AZURE_STORAGE_ACCOUNT"
            --account-key "$AZURE_STORAGE_KEY"
            --destination "$PINAMOD_DIR"
            --source "$AZURE_STORAGE_CONTAINER"
            --no-progress
        env:
        - name: PINAMOD_DIR
          value: /opt/models/pinamod
        - name: AZURE_STORAGE_ACCOUNT
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_STORAGE_ACCOUNT
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_STORAGE_KEY
        - name: AZURE_STORAGE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: AZURE_STORAGE_CONTAINER
        volumeMounts:
        - name: pina-models
          mountPath: /opt/models
      volumes:
      - name: pina-models
        hostPath:
          path: /opt/intellioptics/edge/pinamod-public
          type: Directory
  backoffLimit: 2


