apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"edge-endpoint-noauth-svc","namespace":"intellioptics-edge"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"edge-endpoint-noauth"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-08T06:45:24Z"
  name: edge-endpoint-noauth-svc
  namespace: intellioptics-edge
  resourceVersion: "4691814"
  uid: c5ea76f3-0112-4df4-951d-677da547a323
spec:
  clusterIP: 10.0.197.197
  clusterIPs:
  - 10.0.197.197
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: edge-endpoint-noauth
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
