apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PERSISTENT_VOLUME_NAME}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-file-sc
  csi:
    driver: file.csi.azure.com
    volumeHandle: ${AZURE_FILE_SHARE_NAME}
    volumeAttributes:
      secretName: azure-file-credentials
      shareName: ${AZURE_FILE_SHARE_NAME}
      storageAccount: ${AZURE_STORAGE_ACCOUNT}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-endpoint-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: azure-file-sc
