apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PERSISTENT_VOLUME_NAME}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-file-sc
  csi:
    driver: file.csi.azure.com
    volumeHandle: ${AZURE_FILE_VOLUME_HANDLE}
    volumeAttributes:
      shareName: ${AZURE_FILE_SHARE_NAME}
      secretName: azure-storage-credentials
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-endpoint-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azure-file-sc
