apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PERSISTENT_VOLUME_NAME}
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: ${AZURE_STORAGE_ACCOUNT}#${AZURE_FILE_SHARE}
    volumeAttributes:
      shareName: ${AZURE_FILE_SHARE}
      secretName: azure-storage-credentials
      secretNamespace: ${DEPLOYMENT_NAMESPACE}
    nodeStageSecretRef:
      name: azure-storage-credentials
      namespace: ${DEPLOYMENT_NAMESPACE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edge-endpoint-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: azurefile-csi

