# Cron job to refresh Azure Container Registry credentials
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-creds
spec:
  schedule: "0 */2 * * *"  # Every 2 hours
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: refresh_creds
        spec:
          serviceAccountName: edge-endpoint-service-account
          imagePullSecrets:
            - name: registry-credentials
          containers:
          - name: acr

            command: [
              "/bin/sh",
              "-c",
              "/intellioptics-edge/deploy/bin/refresh-ecr-login.sh"
              ]
            env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-service-principal
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-service-principal
                  key: AZURE_CLIENT_SECRET
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-service-principal
                  key: AZURE_TENANT_ID
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  name: azure-service-principal
                  key: AZURE_SUBSCRIPTION_ID
              optional: true
            - name: ACR_NAME
              value: acrintellioptics
            - name: AZURE_CONTAINER_REGISTRY
              value: acrintellioptics
            - name: ACR_LOGIN_SERVER
              value: acrintellioptics.azurecr.io

          restartPolicy: OnFailure



