# Cron job to refresh our local credentials
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-creds
spec:
  schedule: "0 */2 * * *"  # Every 2 hours
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: refresh_creds
        spec:
          serviceAccountName: edge-endpoint-service-account
          imagePullSecrets:
            - name: registry-credentials
          containers:
          - name: acr
            image: mcr.microsoft.com/azure-cli:2.60.0
            command: [
              "/bin/sh",
              "-c",
              "/intellioptics-edge/deploy/bin/refresh-acr-login.sh"
              ]
            env:
            - name: ACR_NAME
              value: your-acr-name
            - name: ACR_LOGIN_SERVER
              value: your-acr-name.azurecr.io

          restartPolicy: OnFailure



