# Cron job to refresh our local credentials
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-creds
spec:
  schedule: "0 */2 * * *"  # Every 2 hours
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: refresh_creds
        spec:
          serviceAccountName: edge-endpoint-service-account
          imagePullSecrets:
            - name: registry-credentials
          containers:
          - name: acr
            image: mcr.microsoft.com/azure-cli:2.53.0
            imagePullPolicy: IfNotPresent

            command: [
              "/bin/sh",
              "-c",
              "/intellioptics-edge/deploy/bin/refresh-ecr-login.sh"
              ]
            env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: AZURE_CLIENT_ID
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: AZURE_CLIENT_SECRET
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: AZURE_TENANT_ID
            - name: ACR_LOGIN_SERVER
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: ACR_LOGIN_SERVER
            - name: ACR_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: ACR_NAME
            
          restartPolicy: OnFailure



