# Cron job to refresh our local credentials
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-creds
spec:
  schedule: "0 */2 * * *"  # Every 2 hours
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: refresh_creds
        spec:
          serviceAccountName: edge-endpoint-service-account
          imagePullSecrets:
            - name: registry-credentials
          containers:
          - name: registry

            command: [
              "/bin/sh",
              "-c",
              "/intellioptics-edge/deploy/bin/refresh-registry-login.sh"
              ]
            env:
            - name: REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  name: registry-bootstrap-credentials
                  key: server
            - name: REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: registry-bootstrap-credentials
                  key: username
            - name: REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-bootstrap-credentials
                  key: password
            
          restartPolicy: OnFailure



