# Cron job to refresh our local credentials
apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresh-creds
spec:
  schedule: "0 */2 * * *"  # Every 2 hours
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: refresh_creds
        spec:
          serviceAccountName: edge-endpoint-service-account
          imagePullSecrets:
            - name: registry-credentials
          containers:
          - name: acr

            command: [
              "/bin/sh",
              "-c",
              "/intellioptics-edge/deploy/bin/refresh-ecr-login.sh"
              ]
            env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client_id
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: client_secret
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: tenant_id
            
          restartPolicy: OnFailure



