location: ${AZ_LOCATION:-eastus}
name: ${ACI_NAME}
type: Microsoft.ContainerInstance/containerGroups
properties:
  osType: Linux
  restartPolicy: Always

  imageRegistryCredentials:
    - server: ${ACR_LOGIN_SERVER}
      username: ${ACR_USERNAME}
      password: ${ACR_PASSWORD}

  containers:
    - name: ${ACI_CONTAINER_NAME}
      properties:
        image: ${ACR_LOGIN_SERVER}/intellioptics/edge-endpoint:${EDGE_IMAGE_TAG}
        resources:
          requests:
            cpu: 2
            memoryInGB: 4
        ports:
          - port: 6718                  # if your FastAPI exposes this; adjust if needed
        environmentVariables:
          # Non-secrets
          - name: INTELLIOPTICS_ENDPOINT
            value: ${INTELLIOPTICS_ENDPOINT:-https://intellioptics-api-37558.azurewebsites.net}
          - name: MODEL_CACHE_DIR
            value: /tmp/model

          # Secrets (supply at deploy time; DO NOT commit actual values)
          - name: INTELLIOPTICS_API_TOKEN
            secureValue: ${INTELLIOPTICS_API_TOKEN}
          - name: SERVICE_BUS_CONN
            secureValue: ${SERVICE_BUS_CONN}

          # Optional
          - name: SB_IMAGE_QUEUE
            value: ${SB_IMAGE_QUEUE:-image-queries}
          - name: SB_RESULTS_QUEUE
            value: ${SB_RESULTS_QUEUE:-inference-results}
          - name: SB_FEEDBACK_QUEUE
            value: ${SB_FEEDBACK_QUEUE:-feedback}

