name: auto-format
on: pull_request

permissions:
  contents: write

jobs:
  format:
    # Only run for PRs from this repo (not forks)
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipx and Poetry 1.8.3
        run: |
          python -m pip install --upgrade pip pipx
          pipx install "poetry==1.8.3"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install lint dependencies
        run: poetry install --only lint --no-interaction

      - name: Run formatter
        run: ./code-quality/format "app test"

      - name: Check for modified files
        id: git-check
        run: |
          if git diff --quiet; then
            echo "modified=false" >> "$GITHUB_OUTPUT"
          else
            echo "modified=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Push formatting changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name "autoformat-bot"
          git config user.email "autoformatbot@users.noreply.github.com"
          git commit -am "Automatically reformatting code with black and isort"
          git push