name: auto-format

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.8.3"

jobs:
  format:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install Poetry ${{ env.POETRY_VERSION }} (via pip)
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry==${{ env.POETRY_VERSION }}"
          poetry --version

      - name: Install formatting deps
        run: |
          if [ -f Makefile ]; then
            make install-lint || true
          fi
          python -m pip install black ruff isort yamllint || true

      - name: Run formatters
        run: |
          set -e
          if [ -f Makefile ]; then
            make format || true
          else
            black .
            ruff check . --fix || true
            isort . || true
          fi

      - name: Commit changes back to PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format via CI"
          branch: ${{ github.head_ref }}
          file_pattern: |
            **/*.py
            **/*.yaml
            **/*.yml
            **/*.toml
            **/*.md