name: Auto Format

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Auto format on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Poetry 1.8.3 (via pip)
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry==1.8.3"
          poetry --version

      - name: Install formatting deps
        run: |
          if [ -f Makefile ]; then
            make install-lint || true
          fi
          python -m pip install black ruff isort yamllint || true

      - name: Run formatters
        run: |
          set -e
          if [ -f Makefile ]; then
            make format || true
          else
            black .
            ruff check . --fix || true
            isort . || true
          fi

      - name: Commit changes back to PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format via CI"
          branch: ${{ github.head_ref }}
          file_pattern: |
            **/*.py
            **/*.yaml
            **/*.yml
            **/*.toml
            **/*.md