name: build-push-ee-image
# This workflow is split into a separate file and called via workflow_call to enable triggering it
# from other repositories, to test new inference images. 
on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      REGISTRY_URL:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
jobs:
  build-push-edge-endpoint-multiplatform:
    # This used to run on a larger runner, but to use it as a reusable workflow outside of this
    # orgnaization we need it to run on a default github runner. 
    # If we start seeing issues with the default runner again, there are some hacks to delete
    # unwanted software that's installed by default on the github runners to free up space. This is
    # already done in the test-k3s-helm workflow.
    runs-on: ubuntu-latest
    steps:
      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
      - name: Build and Push Multiplatform edge-endpoint Image to ECR
        # This is actually only taking about 4 minutes right now.
        timeout-minutes: 45
        run: REGISTRY_URL=${{ secrets.REGISTRY_URL }} REGISTRY_USERNAME=${{ secrets.REGISTRY_USERNAME }} REGISTRY_PASSWORD=${{ secrets.REGISTRY_PASSWORD }} ./deploy/bin/build-push-edge-endpoint-image.sh
