name: format-lite

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install formatters (no Poetry)
        run: |
          python -m pip install --upgrade pip
          python -m pip install black ruff isort yamllint

      - name: Run formatters
        run: |
          set -e
          black .
          ruff check . --fix || true
          isort . || true

      - name: Commit changes back to PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format (format-lite)"
          branch: ${{ github.head_ref }}
          file_pattern: |
            **/*.py
            **/*.yaml
            **/*.yml
            **/*.toml
            **/*.md