name: format-lite

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install formatters (no Poetry)
        run: |
          python -m pip install --upgrade pip
          python -m pip install black ruff isort yamllint

      - name: Run formatters (exclude vendor/ and cicd/pulumi/)
        run: |
          set -e
          EXCL='(vendor/|cicd/pulumi/)'
          set +e
          black --exclude "$EXCL" .
          ruff check . --fix --exclude vendor --exclude cicd/pulumi
          isort . --profile=black --line-length=120 --skip vendor --skip cicd/pulumi
          set -e

      - name: Commit changes back to PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format (format-lite, excludes vendor/ and cicd/pulumi/)"
          branch: ${{ github.head_ref }}
          file_pattern: |
            **/*.py
            **/*.yaml
            **/*.yml
            **/*.toml
            **/*.md