# yamllint disable rule:comments-indentation
name: sweeper-eeut
# This workflow tears down old EEUT stacks from pulumi.
# We do this as a background sweeper job, because the teardown is VERY slow (~7 minutes for a g4)
# and we don't want to slow down the main pipeline for that.
on:
  schedule:
    # Note cron workflows only run from the main branch.
    - cron: "*/15 * * * *" # Every 15 minutes


    # Note cron workflows only run from the main branch.


    # Note cron workflows only run from the main branch.


    # Note cron workflows only run from the main branch.

        # Note cron workflows only run from the main branch.
  # yamllint enable rule:comments-indentation


  push:
    branches:
      # If you're working on this stuff, name your branch e2e-something and this will run.
      - e2e*
concurrency:
  group: sweeper-eeut
env:
  PYTHON_VERSION: "3.11"

jobs:
  destroy-expired-eeut-stacks:
    #runs-on: ubuntu-22.04  # preferably
    # Currently running on self-hosted because something is wrong with the Azure perms on the GH runners.
    runs-on: self-hosted
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_CICD_PAT }}
    defaults:
      run:
        working-directory: cicd/pulumi
    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Log in to Azure
        uses: azure/login@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export HOME=$(eval echo ~$(whoami))
          echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - name: Check that pulumi is installed and authenticated
        run: |
          set -e
          pulumi whoami

      - name: Destroy old EEUT stacks
        working-directory: cicd/pulumi
        run: |
          ./sweep-destroy-eeut-stacks.sh
