name: Test K3s & Helm (manual)

on:
  # Disable on PR/push for now; run manually when needed
  workflow_dispatch:

jobs:
  noop:
    name: No-op (disabled for PRs)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print note
        run: echo "K3s/Helm test workflow is disabled for PRs; use 'workflow_dispatch' to run it manually."