name: Workflow YAML check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-workflow-files:
    name: check-workflow-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint

      - name: Lint workflow YAMLs (dynamic)
        working-directory: .github/workflows
        run: |
          set -e
          files="$(ls *.yml *.yaml 2>/dev/null || true)"
          if [ -n "$files" ]; then
            echo "Linting files:"
            echo "$files"
            yamllint -c ../.yamllint.yaml $files
          else
            echo "No workflow YAML files found."
          fi